//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr23._107k_sofin_authorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roli
    {
        public int Roli_ID { get; set; }
        public string Rol { get; set; }
        public int Users_ID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
